# myfile=open("hello.txt","w")
# myfile.write("ICATA_CALICUT Full Stack Class")
# myfile.close()
# print("File generated Successfully")
myfile=open("hello.txt","r")
r=myfile.read()
print(r)
myfile.close()